### ISSUE TITLE
Problems with filebeat

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#355]
Currently, filebeat package is not found. From https://ci.suse.de/job/manager-Head-cucumber/566/consoleFull :
```
module.srv.module.suse_manager.libvirt_domain.domain (remote-exec): [ERROR   ]
 Command '[u'systemd-run', u'--scope', u'zypper', u'--non-interactive',
 u'--no-refresh', u'install', u'--auto-agree-with-licenses', u'--name', u'filebeat']'
 failed with return code: 104
(...)
06:34:32 module.srv.module.suse_manager.libvirt_domain.domain (remote-exec):
 Package 'filebeat' not found.
```

Before that, we also has problems with filebeat service not starting. From https://ci.suse.de/job/manager-Head-cucumber/538/consoleFull :
```
14:19:06 module.srv.module.suse_manager.libvirt_domain.domain (remote-exec): [INFO    ]
 Executing command [u'systemctl', 'is-enabled', u'filebeat.service'] in directory
 '/root'
14:19:06 module.srv.module.suse_manager.libvirt_domain.domain (remote-exec): [ERROR   ]
 Service filebeat failed to start
```

**Comment by kkaempf** [comment]
It's part of the log analysis stack (which I'm currently in the process of upgrading).

**Comment by kkaempf** [comment]
Problem is a broken Go in OBS, all go packages don't build currently :confused:

**Comment by moio** [comment]
I've been on it with Jordi and others since some days https://lists.opensuse.org/opensuse-go/2018-05/msg00000.html

**Comment by kkaempf** [comment]
Yes, exactly this one

**Comment by moio** [comment]
Problem has been addressed on the Go side, but it seems the filebeat package has disappeared from security:logging.

https://build.opensuse.org/project/show/security:logging

@kkaempf, do you have insights?

**Comment by MalloZup** [comment]
@kkaempf  why we don't move filebeat on docker container and use the upstream ones?

**Comment by kkaempf** [comment]
@moio go building is still broken on OBS it seems

@MalloZup filebeat needs direct log file access and must be installed on the logging host

**Comment by kkaempf** [comment]
beats package is fixed and submitted

**Comment by Bischoff** [comment]
Seems to work. Closing.
